from .cargo import CargoForm
from .producto import ProductoForm
from .centro import CentroForm
from .causa_raiz import CausaRaizForm
from .puesto_trabajo import PuestoTrabajoForm
from .tipo_merma import TipoMermaForm
from .unidad_medida import UnidadMedidaForm
from .turno import TurnoForm
from .colaborador import ColaboradorForm
from .merma import MermaForm
from .material import MaterialForm
