# Generated by Django 4.2.17 on 2024-12-21 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_cargo', models.CharField(max_length=255)),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tbl_cargo',
            },
        ),
        migrations.CreateModel(
            name='Centro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_centro', models.CharField(max_length=255)),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tbl_centro',
            },
        ),
    ]
