# Generated by Django 4.2.17 on 2024-12-21 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenedores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CausaRaiz',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_causa_raiz', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tbl_causa_raiz',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_producto', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tbl_producto',
            },
        ),
        migrations.CreateModel(
            name='PuestoTrabajo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_puesto_trabajo', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tbl_puesto_trabajo',
            },
        ),
        migrations.CreateModel(
            name='TipoMerma',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_tipo_merma', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tbl_tipo_merma',
            },
        ),
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_unidad_medida', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tbl_unidad_medida',
            },
        ),
    ]
