# Generated by Django 4.2.17 on 2025-02-04 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenedores', '0002_causaraiz_producto_puestotrabajo_tipomerma_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('hora_inicio', models.CharField(max_length=10)),
                ('hora_fin', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'tbl_turno',
            },
        ),
    ]
