# Generated by Django 4.2.17 on 2025-02-04 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenedores', '0003_turno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='hora_fin',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='turno',
            name='hora_inicio',
            field=models.TimeField(),
        ),
    ]
