# Generated by Django 4.2.17 on 2025-02-08 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mantenedores', '0004_alter_turno_hora_fin_alter_turno_hora_inicio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('rut', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=255)),
                ('correo', models.CharField(max_length=255)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenedores.cargo')),
            ],
            options={
                'db_table': 'tbl_colaborador',
            },
        ),
    ]
