# Generated by Django 4.2.17 on 2025-02-09 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mantenedores', '0005_colaborador'),
    ]

    operations = [
        migrations.CreateModel(
            name='Merma',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenedores.tipomerma')),
            ],
            options={
                'db_table': 'tbl_merma',
            },
        ),
    ]
