# Generated by Django 4.2.17 on 2025-02-09 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mantenedores', '0006_merma'),
    ]

    operations = [
        migrations.RenameField(
            model_name='merma',
            old_name='cargo',
            new_name='tipo_merma',
        ),
    ]
