# Generated by Django 4.2.17 on 2025-02-09 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenedores', '0007_rename_cargo_merma_tipo_merma'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('formato', models.CharField(max_length=255)),
                ('peso_caja', models.CharField(max_length=255)),
                ('golpes', models.CharField(max_length=255)),
                ('bajadas', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tbl_material',
            },
        ),
    ]
